name: Run Test
on: push
jobs:
    job-test:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v3
            - name: Install Node
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Npm install
              run: npm ci
            - name: Run testes
              run: npm tests